# Generated by Django 2.2.5 on 2019-09-11 06:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('occupation', models.CharField(max_length=100, verbose_name='occupation')),
                ('address', models.CharField(max_length=100, verbose_name='address(town)')),
                ('country', models.CharField(max_length=100, verbose_name='address(town)')),
                ('work_place', models.CharField(max_length=100, verbose_name='work place')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
