# Generated by Django 2.2.5 on 2019-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='work_place',
            field=models.CharField(max_length=100, null=True, verbose_name='work place'),
        ),
    ]
