# Generated by Django 2.2.5 on 2019-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_auto_20190911_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='address(town)'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='occupation',
            field=models.CharField(max_length=100, null=True, verbose_name='occupation'),
        ),
    ]
